Handle WGET issues better

diff --git a/.github/workflows/maven-branches.yml b/.github/workflows/maven-branches.yml
--- a/.github/workflows/maven-branches.yml
+++ b/.github/workflows/maven-branches.yml
@@ -168,7 +168,14 @@ jobs:
       pull-requests: read
     steps:
       - name: Collect http://maven.apache.org/xsd
-        run: wget -np -rN -l 1 --no-verbose http://maven.apache.org/xsd
+        run: |
+          set +e
+          wget -np -rN -l 1 --no-verbose http://maven.apache.org/xsd
+          case $? in
+            0) echo "Success";;
+            8) echo "No changes";;
+            *) echo "Failed";;
+          esac
 
       - name: Zipup XSDs
         run: |
@@ -274,7 +281,7 @@ jobs:
         run: ls -Alh ${{ vars.COLLECTOR }}-*.*
 
   Sharepoint:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
     needs: [Date, MakeISO]
     env:
         GH_TOKEN: ${{ github.token }}
